name: Node.js CI/CD
run-name: ${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      name:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    # GitHub 官方提供的镜像
    steps:
    - uses: actions/checkout@v4
    # 允许镜像系统读取仓库
    - run: npm i
    # Or npm ci (need package-lock.json)
    - run: npm run build

    - name: Rename main1 to main
      run: |
        if [ -f main1.js ]; then
          mv main1.js main.js
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: markmap-fileviews
        path: |
          main.js
          manifest.json
          styles.css
